function init(){
  require('aws-sdk').config.region = process.env.AWS_REGION;
  process.env.USER_TABLE = `serverless-sample-user-${process.env.AWS_STAGE}`;

  //Note: in reality you would have a known dns name/pattern rather than the random address generated by api-g
  let stage = process.env.AWS_STAGE;
  if(stage === 'dev') {
    process.env.URL = `https://tl0orf5x0a.execute-api.eu-west-1.amazonaws.com/dev`;
  } else if (stage == 'test') {
    process.env.URL = `https://ne2uod40r5.execute-api.eu-west-1.amazonaws.com/test`;    
  } else {
    throw new Error(`Stage is not configured for testing: ${stage}`);
  }

  console.log('api url: ', process.env.URL);
}

module.exports = {
  init
};